require('dotenv').config();
const express=require('express');const path=require('path');const fs=require('fs');const crypto=require('crypto');const tls=require('tls');const Razorpay=require('razorpay');
const app=express();const PORT=Number(process.env.PORT||3000);const DATA=path.join(__dirname,'data');const ORDERS=path.join(DATA,'orders.json');const PENDING=path.join(DATA,'pending-payments.json');if(!fs.existsSync(DATA))fs.mkdirSync(DATA,{recursive:true});if(!fs.existsSync(ORDERS))fs.writeFileSync(ORDERS,'[]');if(!fs.existsSync(PENDING))fs.writeFileSync(PENDING,'{}');
let products=JSON.parse(fs.readFileSync(path.join(DATA,'products.json'),'utf8'));
function saveProducts(){fs.writeFileSync(path.join(DATA,'products.json'),JSON.stringify(products,null,2))}const KEY_ID=process.env.RAZORPAY_KEY_ID||'';const KEY_SECRET=process.env.RAZORPAY_KEY_SECRET||'';const razorpay=KEY_ID&&KEY_SECRET?new Razorpay({key_id:KEY_ID,key_secret:KEY_SECRET}):null;
const GOOGLE_SCRIPT_URL=process.env.GOOGLE_SCRIPT_URL||'';const EMAIL_USER=process.env.EMAIL_USER||'maaastrologyindia@gmail.com';const EMAIL_FROM=process.env.EMAIL_FROM||EMAIL_USER;const EMAIL_TO=process.env.EMAIL_TO||'maaastrologyindia@gmail.com';const EMAIL_APP_PASSWORD=process.env.EMAIL_APP_PASSWORD||'';const ADMIN_PASSWORD=process.env.ADMIN_PASSWORD||'change-this-password';const sessions=new Set();
app.use(express.json({limit:'100kb'}));app.use(express.static(path.join(__dirname,'public')));
const money=n=>Math.round(Number(n)*100)/100;
const PACKAGE_PRICES={1:399,2:699,3:999,4:1299};
const PREPAID_DISCOUNT=50;
function readPending(){return JSON.parse(fs.readFileSync(PENDING,'utf8'))}function writePending(x){fs.writeFileSync(PENDING,JSON.stringify(x,null,2))}function reserveStock(items){for(const i of items){const p=products.find(x=>x.id===i.id);if(!p||p.stock<i.qty)throw new Error(`${p?.name||'Product'} is out of stock or has insufficient stock.`)}for(const i of items){const p=products.find(x=>x.id===i.id);p.stock-=i.qty}saveProducts()}function calc(items,coupon,payment){
  const clean=[];
  for(const x of Array.isArray(items)?items:[]){
    const p=products.find(p=>p.id===x.id);
    const q=Math.max(0,Math.min(4,Math.floor(Number(x.qty)||0)));
    if(p&&q)clean.push({id:p.id,name:p.name,qty:q,unitPrice:p.price});
  }
  const qty=clean.reduce((s,x)=>s+x.qty,0);
  const subtotal=PACKAGE_PRICES[qty]||0;
  const couponCode=String(coupon||'').trim().toUpperCase();
  const couponDiscount=couponCode==='WELCOME10'&&qty>=2?money(subtotal*.10):0;
  const prepaidDiscount=payment==='online'?PREPAID_DISCOUNT:0;
  const total=Math.max(0,money(subtotal-couponDiscount-prepaidDiscount));
  return {items:clean,quantity:qty,subtotal,couponDiscount,prepaidDiscount,total};
}
function readOrders(){return JSON.parse(fs.readFileSync(ORDERS,'utf8'))}function writeOrders(x){fs.writeFileSync(ORDERS,JSON.stringify(x,null,2))}function addOrder(o){const a=readOrders();a.unshift(o);writeOrders(a);return o}
function smtpRead(socket,codes){return new Promise((resolve,reject)=>{let b='';const f=d=>{b+=d.toString();const ls=b.split(/\r?\n/).filter(Boolean);const last=ls[ls.length-1];if(!last||!/^[0-9]{3}[ -]/.test(last)||last[3]!==' ')return;const c=Number(last.slice(0,3));socket.off('data',f);if(codes.includes(c))resolve({code:c});else reject(new Error('SMTP '+c));};socket.on('data',f);socket.once('error',reject)})}async function smtpCmd(s,c,codes){s.write(c+'\r\n');return smtpRead(s,codes)}
async function email(to,subject,text){if(!EMAIL_APP_PASSWORD||!to)return;const s=tls.connect({host:'smtp.gmail.com',port:465,servername:'smtp.gmail.com'});await new Promise((res,rej)=>{s.once('secureConnect',res);s.once('error',rej)});await smtpRead(s,[220]);await smtpCmd(s,'EHLO localhost',[250]);await smtpCmd(s,'AUTH LOGIN',[334]);await smtpCmd(s,Buffer.from(EMAIL_USER).toString('base64'),[334]);await smtpCmd(s,Buffer.from(EMAIL_APP_PASSWORD.replace(/\s/g,'')).toString('base64'),[235]);await smtpCmd(s,`MAIL FROM:<${EMAIL_FROM}>`,[250]);await smtpCmd(s,`RCPT TO:<${to}>`,[250,251]);const headers=[`From: Maa Astrology <${EMAIL_FROM}>`,`To: ${to}`,`Subject: ${subject}`,'MIME-Version: 1.0','Content-Type: text/plain; charset=UTF-8'].join('\r\n');await smtpCmd(s,'DATA',[354]);s.write((headers+'\r\n\r\n'+text).replace(/^\./gm,'..')+'\r\n.\r\n');await smtpRead(s,[250]);s.write('QUIT\r\n');s.end()}
async function notify(o){const lines=[`Order: ${o.id}`,`Customer: ${o.customerName}`,`Mobile: ${o.mobile}`,`Email: ${o.email||''}`,`Items: ${o.items.map(i=>i.name+' × '+i.qty).join(', ')}`,`Subtotal: ₹${o.subtotal}`,`Coupon discount: ₹${o.couponDiscount}`,`Prepaid discount: ₹${o.prepaidDiscount}`,`Total: ₹${o.amount}`,`Payment: ${o.payment}`,`Address: ${o.address}, ${o.city}, ${o.state} - ${o.pincode}`];const text=lines.join('\n');try{await email(EMAIL_TO,'New Maa Astrology Order — '+o.id,text);if(o.email)await email(o.email,'Maa Astrology Order Confirmation — '+o.id,'Thank you for ordering from Maa Astrology.\n\n'+text)}catch(e){console.error('email',e.message)}}
async function forward(o){if(!GOOGLE_SCRIPT_URL)return;const r=await fetch(GOOGLE_SCRIPT_URL,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(o)});if(!r.ok)throw new Error('Google Script HTTP '+r.status)}
app.get('/api/products',(req,res)=>res.json(products));
app.post('/api/submit-order',async(req,res)=>{try{const b=req.body||{},c=calc(b.items,b.coupon,b.payment==='online'?'online':'cod');if(!c.quantity||!PACKAGE_PRICES[c.quantity])return res.status(400).json({error:'Order must contain 1 to 4 bracelets.'});if(!String(b.customerName||'').trim()||!String(b.mobile||'').trim()||!String(b.address||'').trim()||!String(b.city||'').trim()||!String(b.state||'').trim()||!String(b.pincode||'').trim())return res.status(400).json({error:'Please complete all required delivery details.'});reserveStock(c.items);const o={id:'MAA-'+Date.now().toString(36).toUpperCase(),createdAt:new Date().toISOString(),customerName:String(b.customerName||'').slice(0,120),mobile:String(b.mobile||'').slice(0,30),email:String(b.email||'').slice(0,160),address:String(b.address||'').slice(0,300),city:String(b.city||'').slice(0,100),state:String(b.state||'').slice(0,100),pincode:String(b.pincode||'').slice(0,10),...c,coupon:c.couponDiscount?'WELCOME10':'',payment:'cod',amount:c.total,status:'NEW'};addOrder(o);try{await forward(o)}catch(e){console.error('forward',e.message)}notify(o);res.json({success:true,order_id:o.id})}catch(e){console.error(e);res.status(e.message.includes('stock')?409:500).json({error:e.message.includes('stock')?e.message:'Unable to submit order.'})}});
app.post('/api/create-order',async(req,res)=>{try{if(!razorpay)return res.status(503).json({error:'Razorpay is not configured on this server yet.'});const b=req.body||{},c=calc(b.items,b.coupon,'online');if(!c.quantity||!PACKAGE_PRICES[c.quantity])return res.status(400).json({error:'Order must contain 1 to 4 bracelets.'});for(const i of c.items){const p=products.find(x=>x.id===i.id);if(!p||p.stock<i.qty)return res.status(409).json({error:`${p?.name||'Product'} is out of stock or has insufficient stock.`})}const ro=await razorpay.orders.create({amount:Math.round(c.total*100),currency:'INR',receipt:'maa_'+Date.now(),notes:{quantity:String(c.quantity),coupon:c.couponDiscount?'WELCOME10':''}});const pending=readPending();pending[ro.id]={createdAt:new Date().toISOString(),customer:{customerName:b.customerName,mobile:b.mobile,email:b.email,address:b.address,city:b.city,state:b.state,pincode:b.pincode},items:c.items,coupon:c.couponDiscount?'WELCOME10':'',...c};writePending(pending);res.json({key_id:KEY_ID,order_id:ro.id,amount:ro.amount,currency:ro.currency})}catch(e){console.error(e);res.status(500).json({error:'Unable to create payment order.'})}});
app.post('/api/verify-payment',async(req,res)=>{try{if(!KEY_SECRET)return res.status(503).json({error:'Razorpay secret is not configured.'});const b=req.body||{},pending=readPending(),c=pending[b.razorpay_order_id];if(!c)return res.status(400).json({error:'Payment session expired or not found. Please start checkout again.'});const expected=crypto.createHmac('sha256',KEY_SECRET).update(`${b.razorpay_order_id}|${b.razorpay_payment_id}`).digest('hex');if(expected!==b.razorpay_signature)return res.status(400).json({error:'Payment signature verification failed.'});if(readOrders().some(o=>o.razorpay_payment_id===b.razorpay_payment_id))return res.status(409).json({error:'This payment has already been processed.'});reserveStock(c.items);const o={id:'MAA-'+Date.now().toString(36).toUpperCase(),createdAt:new Date().toISOString(),...c.customer,items:c.items,quantity:c.quantity,subtotal:c.subtotal,couponDiscount:c.couponDiscount,prepaidDiscount:c.prepaidDiscount,total:c.total,coupon:c.coupon,payment:'online',amount:c.total,status:'PAID',razorpay_order_id:b.razorpay_order_id,razorpay_payment_id:b.razorpay_payment_id};addOrder(o);delete pending[b.razorpay_order_id];writePending(pending);try{await forward(o)}catch(e){console.error('forward',e.message)}notify(o);res.json({success:true,order_id:o.id})}catch(e){console.error(e);res.status(e.message.includes('stock')?409:500).json({error:e.message.includes('stock')?e.message:'Unable to verify payment.'})}});
app.post('/api/admin/login',(req,res)=>{if(req.body?.password!==ADMIN_PASSWORD)return res.status(401).json({error:'Invalid password.'});const t=crypto.randomBytes(24).toString('hex');sessions.add(t);res.json({token:t})});function auth(req,res,next){const t=(req.headers.authorization||'').replace('Bearer ','');if(!sessions.has(t))return res.status(401).json({error:'Unauthorized'});next()}
app.patch('/api/admin/products/:id',auth,(req,res)=>{const p=products.find(x=>x.id===req.params.id);if(!p)return res.status(404).json({error:'Not found'});if(req.body.stock!==undefined)p.stock=Math.max(0,Math.floor(Number(req.body.stock)||0));if(req.body.tag!==undefined)p.tag=String(req.body.tag).slice(0,80);saveProducts();res.json({success:true,product:p})});
app.get('/api/admin/orders',auth,(req,res)=>res.json({orders:readOrders()}));app.get('/api/admin/orders/:id',auth,(req,res)=>{const o=readOrders().find(x=>x.id===req.params.id);if(!o)return res.status(404).json({error:'Not found'});res.json({order:o})});app.patch('/api/admin/orders/:id',auth,(req,res)=>{const a=readOrders(),o=a.find(x=>x.id===req.params.id);if(!o)return res.status(404).json({error:'Not found'});o.status=['NEW','PAID','PROCESSING','SHIPPED','DELIVERED','CANCELLED'].includes(req.body.status)?req.body.status:o.status;writeOrders(a);res.json({success:true,order:o})});
app.listen(PORT,()=>console.log(`Maa Astrology running on http://localhost:${PORT}`));
